version: "3.3"

services:
  rabbit-mq:
    image: bitnami/rabbitmq:latest
    restart: always
    hostname: "rabbit_mq_host"
    networks:
      - hw-proj

  db:
    image: postgres:latest
    ports:
      - "54321:5432"
    hostname: "db_host"
    environment:
      - POSTGRES_DB=hwproj
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - hw-proj

  queue:
    build: ./queue
    restart: always
    hostname: "queue_host"
    networks:
      - hw-proj
    depends_on:
      - rabbit-mq

  backend:
    build: ./WebServerApi
    restart: always
    ports:
      - "10003:10003"
    hostname: "backend_host"
    networks:
      - hw-proj
    depends_on:
      - db

  frontend:
    build: ./WebServer
    restart: always
    ports:
      - "10002:10002"
    hostname: "frontend_host"
    networks:
      - hw-proj
    depends_on:
      - db
      - backend

  repository:
    build:
      context: ./repository
      dockerfile: ./init.Dockerfile
    restart: always
    hostname: "repository_host"
    command: "--mode api"
    networks:
      - hw-proj
    depends_on:
      - db

  db-init:
    build:
      context: ./repository
      dockerfile: ./init.Dockerfile
    restart: always
    command: "--mode init"
    networks:
      - hw-proj
    depends_on:
      - db

networks:
  hw-proj:
    driver: bridge
